### ISSUE TITLE
Doesn't display defaultTime until key pressed.

### ISSUE THREAD

**Issue by JamesUoM** [kbwood/timeentry#17]
Using http://keith-wood.name/timeEntryBasics.html

The time is not display until a numeric key is pressed when the field has focus.

Ubuntu 14.04 x64
Chromium 41
firefox 38

**Comment by kbwood** [comment]
The time is not displayed by default. If you wish to set an initial value for the field you can do it in the HTML itself, or through code with the 'setTime' method.
