### ISSUE TITLE
Broken on jQuery 1.9.0

### ISSUE THREAD

**Issue by starkovv** [kbwood/timeentry#7]
It seems it does not work with jQuery 1.9.0.

After I've updated jQuery from 1.8.2 to 1.9.0 it started to raise error.
In firebug console:

```
TypeError: $.browser is undefined
if ($.browser.mozilla) {
```

**Comment by JakobJingleheimer** [comment]
I seem to get this error regardless of jQuery version (and I've definitely included jQuery before this lib).

**Comment by kbwood** [comment]
$.browser was removed in jQuery 1.9. The plugin should work with previous versions. I'll release an update in the near future.

**Comment by JakobJingleheimer** [comment]
It still works (even though I get that console error)

**Comment by nathany** [comment]
Fyi, you can use Jquery Migrate https://github.com/jquery/jquery-migrate to provide the `$.browser` functionality in JQuery 1.9+. Still hoping to get everything upgraded so that we don't need to include Migrate.

**Comment by nathany** [comment]
This is resolved in the 1.5.1 release.

**Comment by JakobJingleheimer** [comment]
Appears to be fixed. Thanks!

**Comment by kbwood** [comment]
Yes, that was the main purpose of this release.
